CHAPTER_LOOKUP = {
    "01": "Live animals",
    "02": "Meat and edible meat offal",
    "03": "Fish and crustaceans, molluscs and aquatic invertebrates",
    "04": "Dairy produce; birds' eggs; natural honey",
    "05": "Products of animal origin, not elsewhere specified",
    "06": "Live trees and other plants; bulbs, roots, cut flowers",
    "07": "Edible vegetables and certain roots and tubers",
    "08": "Edible fruit and nuts; peel of citrus fruit or melons",
    "09": "Coffee, tea, maté and spices",
    "10": "Cereals",
    "11": "Products of the milling industry; malt; starches; inulin",
    "12": "Oil seeds and oleaginous fruits; grains, seeds; medicinal plants",
    "13": "Lac; gums, resins and other vegetable saps and extracts",
    "14": "Vegetable plaiting materials; vegetable products n.e.s.",
    "15": "Animal or vegetable fats and oils; cleavage products; waxes",
    "16": "Preparations of meat, fish or crustaceans",
    "17": "Sugars and sugar confectionery",
    "18": "Cocoa and cocoa preparations",
    "19": "Preparations of cereals, flour, starch or milk; pastrycooks' products",
    "20": "Preparations of vegetables, fruit, nuts or other parts of plants",
    "21": "Miscellaneous edible preparations",
    "22": "Beverages, spirits and vinegar",
    "23": "Residues and waste from food industries; prepared animal fodder",
    "24": "Tobacco and manufactured tobacco substitutes",
    "25": "Salt; sulphur; earths and stone; plastering materials; lime and cement",
    "26": "Ores, slag and ash",
    "27": "Mineral fuels, mineral oils and products of their distillation",
    "28": "Inorganic chemicals; compounds of precious metals; isotopes",
    "29": "Organic chemicals",
    "30": "Pharmaceutical products",
    "31": "Fertilizers",
    "32": "Tanning or dyeing extracts; dyes; pigments; paints; putty",
    "33": "Essential oils; perfumery, cosmetic or toilet preparations",
    "34": "Soap, organic surface-active agents, washing preparations",
    "35": "Albuminoidal substances; modified starches; glues; enzymes",
    "36": "Explosives; pyrotechnic products; matches",
    "37": "Photographic or cinematographic goods",
    "38": "Miscellaneous chemical products",
    "39": "Plastics and articles thereof",
    "40": "Rubber and articles thereof",
    "41": "Raw hides and skins (other than furskins) and leather",
    "42": "Articles of leather; saddlery; travel goods; handbags",
    "43": "Furskins and artificial fur; manufactures thereof",
    "44": "Wood and articles of wood; wood charcoal",
    "45": "Cork and articles of cork",
    "46": "Manufactures of straw, esparto; basketware and wickerwork",
    "47": "Pulp of wood or other fibrous cellulosic material; waste",
    "48": "Paper and paperboard; articles of paper pulp or paper",
    "49": "Printed books, newspapers, pictures and other products of printing",
    "50": "Silk",
    "51": "Wool, fine or coarse animal hair; yarn and woven fabric",
    "52": "Cotton",
    "53": "Other vegetable textile fibres; paper yarn and fabrics",
    "54": "Man-made filaments",
    "55": "Man-made staple fibres",
    "56": "Wadding, felt; twine, cordage, ropes and cables",
    "57": "Carpets and other textile floor coverings",
    "58": "Special woven fabrics; tufted textile fabrics; lace; tapestries",
    "59": "Impregnated, coated, covered textile fabrics; industrial textiles",
    "60": "Knitted or crocheted fabrics",
    "61": "Articles of apparel and clothing accessories, knitted or crocheted",
    "62": "Articles of apparel and clothing accessories, not knitted",
    "63": "Other made-up textile articles; sets; worn clothing and rags",
    "64": "Footwear, gaiters and the like; parts of such articles",
    "65": "Headgear and parts thereof",
    "66": "Umbrellas, walking-sticks, whips, riding-crops; parts",
    "67": "Prepared feathers; artificial flowers; articles of human hair",
    "68": "Articles of stone, plaster, cement, asbestos, mica or similar",
    "69": "Ceramic products",
    "70": "Glass and glassware",
    "71": "Natural or cultured pearls; precious stones; precious metals",
    "72": "Iron and steel",
    "73": "Articles of iron or steel",
    "74": "Copper and articles thereof",
    "75": "Nickel and articles thereof",
    "76": "Aluminium and articles thereof",
    "77": "Reserved for possible future use",
    "78": "Lead and articles thereof",
    "79": "Zinc and articles thereof",
    "80": "Tin and articles thereof",
    "81": "Other base metals; cermets; articles thereof",
    "82": "Tools, implements, cutlery, spoons and forks; base metal parts",
    "83": "Miscellaneous articles of base metal",
    "84": "Nuclear reactors, boilers, machinery and mechanical appliances",
    "85": "Electrical machinery and equipment; sound/TV recorders",
    "86": "Railway or tramway locomotives, rolling-stock and parts",
    "87": "Vehicles other than railway or tramway; parts and accessories",
    "88": "Aircraft, spacecraft, and parts thereof",
    "89": "Ships, boats and floating structures",
    "90": "Optical, photographic, cinematographic, medical instruments",
    "91": "Clocks and watches and parts thereof",
    "92": "Musical instruments; parts and accessories",
    "93": "Arms and ammunition; parts and accessories",
    "94": "Furniture; bedding; lamps; prefabricated buildings",
    "95": "Toys, games and sports requisites; parts and accessories",
    "96": "Miscellaneous manufactured articles",
    "97": "Works of art, collectors' pieces and antiques",
    "98": "Special classification provisions",
    "99": "Special classification provisions",
}


def get_chapter_name(chapter2: str) -> str:
    code = str(chapter2).zfill(2)
    return CHAPTER_LOOKUP.get(code, f"Chapter {code}")
